name: Haskell CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    strategy: 
      matrix:
        resolver: 
          - stack
          - stack-lts-14.12
          - stack-lts-13.26

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1  
    
    - name: Install system dependencies 
      run: |
        sudo apt-get install libpcre3-dev

    - name: Install the Haskell Stack 
      run: |
        mkdir -p ~/.local/bin
        curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}
        restore-keys: |
            ${{ runner.os }}-stack
            ${{ runner.os }}

    - name: Install GHC 
      run: |
        export PATH=$HOME/.local/bin:$PATH
        stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal --install-ghc setup

    - name: Install dependencies
      run: |
        export PATH=$HOME/.local/bin:$PATH
        stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --flag uow-apis:build-exe --only-dependencies --fast
        
    - name: Build 
      run: |
        export PATH=$HOME/.local/bin:$PATH
        stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal build --flag uow-apis:build-exe --fast
        stack --stack-yaml=${{ matrix.resolver }}.yaml --no-terminal install --flag uow-apis:build-exe --fast --local-bin-path=${{ github.workspace }}/bin
    - name: get shortsha
      id: vars
      run: |
       echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})
    - name: Create release 
      id: create_release
      uses: actions/create-release@v1
      if: ${{ matrix.resolver == 'stack' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHORTSHA: ${{ steps.vars.outputs.sha_short }}
      with:
        tag_name: latest
        release_name: Release $SHORTSHA
        draft: false
        prerelease: false

    - name: Upload release asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1
      if: ${{ matrix.resolver == 'stack' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ github.workspace }}/bin/uow-util
        asset_name: uow-util
        asset_content_type: application/octet-stream
